---
- hosts: Windows
  name: This is my Windows patching playbook
  tasks:
    - name: Install Windows Updates
      win_updates:
        category_names: "{{ categories }}"
        reboot: yes
#       reboot: '{{ reboot_server | default(yes) }}'

